name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements.txt
      - run: |
          pip install pylint
          curl https://raw.githubusercontent.com/ripe-tech/pylint-config/master/pylintrc --output pylintrc
          PYTHONPATH=src pylint src/ripe
      - run: |
          pip install black
          black . --check --config ./pyproject.toml
      - run: python setup.py test
      - run: |
          pip install coveralls
          coverage run --source=ripe --omit="src/ripe/test/*" setup.py test
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
